export const FOOD_EXPERIENCE_DATA = {
  heading: "Our Menu Throughout The Day",
  subtitle: "Freshly prepared every day using authentic Tamil Nadu recipes.",
  meals: [
    {
      id: "breakfast",
      title: "Breakfast",
      timing: "6:30 AM – 11:00 AM",
      items: [
        "Idly",
        "Dosa",
        "Poori",
        "Paniyaram",
        "Onion Dosa",
        "Podi Dosa",
        "Ghee Dosa",
        "Egg Dosa",
        "Special Dosa",
      ],
      link: "/menu",
      buttonText: "View Menu",
    },
    {
      id: "lunch",
      title: "Lunch",
      timing: "12:00 PM – 3:30 PM",
      items: [
        "Veg Meals",
        "Non Veg Meals",
        "Tomato Rice",
        "Sambar Rice",
        "Ghee Rice",
        "CM's Chicken",
        "Pepper Chicken",
        "Chilli Chicken",
        "Boiled Egg",
        "Egg Bhurji",
      ],
      link: "/menu",
      buttonText: "View Menu",
    },
    {
      id: "dinner",
      title: "Dinner",
      timing: "6:30 PM – 9:00 PM",
      items: [
        "Chapathi",
        "Dosa",
        "Ghee Rice",
        "Curd Rice",
        "CM's Chicken",
        "Pepper Chicken",
        "Paniyaram",
      ],
      link: "/menu",
      buttonText: "View Menu",
    },
  ],
};
